# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z_iw5IoGOXdXmsO1-JRSuX3qGhhuCt6L
"""



from keras.layers import Flatten, Input
from keras.models import Model
from keras.applications.vgg16 import VGG16
import glob
import cv2
import numpy as np
from google.colab import drive
drive.mount('/content/gdrive/')
path_to_images = '/content/gdrive/My Drive/Colab Notebooks/letter/'
paths_list = sorted(glob.glob(path_to_images + "/*.jpg"))  
X=[]
for i, image_path in enumerate(paths_list):
    image = cv2.imread(image_path)
    image_type = image_path.split('/')[-1][0]
    if(image_type=="c"):        #change "c" to "o" when we want to store the features of "o"
      image_resized = cv2.resize(image, (224, 224))
      X.append(image_resized)

X=np.array(X)
input = Input(shape=(224, 224, 3), name = 'image_input')
vgg_model = VGG16(weights='imagenet', include_top=False)

our_feats = vgg_model(input)
our_feats = Flatten()(our_feats)

model = Model(inputs=input, outputs=our_feats)
model.summary() # See our model

#store these 2 label features "o" and "c" into 2 npy files by 
output_feats = model.predict(X) # Extract features of our images
path_to_features = '/content/gdrive/My Drive/Colab Notebooks/features/'
output_feats=np.load(path_to_features+'c.npy')
output_featsc=np.load(path_to_features+'truec.npy')


#shuffle features and store them to txt
with open('/content/gdrive/My Drive/Colab Notebooks/features/features.txt', 'w') as f:
  for (x,y) in zip(output_feats,output_featsc):
    f.write("\n")
    f.write("o")
    f.write("\n")
    for j in x:
      f.write(str(j))
      f.write(",")    
    f.write("\n")
    f.write("c")
    f.write("\n")
    for c in y:
      f.write(str(c))
      f.write(",")


